services:
  - type: web
    name: newyear-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: USER_ID
        sync: false
    healthCheckPath: /
    autoDeploy: true
